name: Arquillian-Cube Maven Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    paths-ignore:
      - 'doc/**'
      - '.circleci/**'
      - '.travis/**'
env:
  # failsafe.groups configuration depends on the env setup.
  FAILSAFE_GROUPS: ''

jobs:
  build:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 90
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        java: ['8']

    steps:
      - name: Setup Minikube
        uses: manusa/actions-setup-minikube@v2.9.0
        with:
          driver: docker
          container runtime: containerd
          minikube version: 'v1.30.1'
          kubernetes version: 'v1.27.1'
          github token: ${{ secrets.GITHUB_TOKEN }}
          start args: "--memory='4gb' --cpus='2'"
        env:
          FAILSAFE_GROUPS: "-Dfailsafe.groups=org.arquillian.cube.docker.impl.requirement.RequiresDocker"
      - name: Enable minikube registry
        run: |
          minikube addons enable registry
          kubectl port-forward --namespace kube-system service/registry 5000:80 &
      - name: Stop minikube # this needs to be addressed again after kubernetes tests got fixed
        run: |
          minikube stop
      - name: Checkout arquillian-cube
        uses: actions/checkout@v4
      - uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'adopt'
      - name: Build with Maven Java ${{ matrix.java }}
        run: |
          mvn -fae clean install ${{ env.FAILSAFE_GROUPS }}
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: surefire-reports-${{ matrix.os }}-${{ matrix.java }}
          path: '${{ github.workspace }}/**/surefire-reports/*.*'
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: server-logs-${{ matrix.os }}-${{ matrix.java }}
          path: '${{ github.workspace }}/**/*.log'
