name: Java CI with Maven

on:
  pull_request:
    branches: [ "master" ]

jobs:
  
  jdk-11-build:
    name: Integration - JDK 11
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B clean install

      - name: Store test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: target/surefire-reports

  docker-build:
    name: Docker integration
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Maven pre-fetch dependencies
        run: mvn verify -q -U -DskipTests

      - name: Maven build
        run: mvn clean package -Dfailsafe.groups=org.arquillian.cube.docker.impl.requirement.RequiresDocker

      - name: Store test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: target/surefire-reports

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: circleci-arquillian-cube-${{ hashFiles('pom.xml') }}
